package testgen

import (
	"context"
	"fmt"
	"testing"

	"github.com/efebarandurmaz/anvil/internal/agents"
	"github.com/efebarandurmaz/anvil/internal/ir"
	"github.com/efebarandurmaz/anvil/internal/plugins"
)

// TestExampleOutput demonstrates the actual output generated by TestGen.
func TestExampleOutput(t *testing.T) {
	tg := New()

	// Sample graph mimicking a COBOL calculator program
	graph := &ir.SemanticGraph{
		Modules: []*ir.Module{{
			Name:     "CALCULATOR",
			Path:     "calculator.cbl",
			Language: "cobol",
			Functions: []*ir.Function{
				{Name: "ADD-NUMBERS"},
				{Name: "SUBTRACT-NUMBERS"},
			},
		}},
		CallGraph: &ir.CallGraph{},
	}

	result, err := tg.Run(context.Background(), &agents.AgentContext{
		Graph:    graph,
		Registry: plugins.NewRegistry(),
		Params: map[string]string{
			"target":          "typescript",
			"generated_files": "[]",
		},
	})

	if err != nil {
		t.Fatal(err)
	}

	// Print example output for documentation
	if testing.Verbose() {
		fmt.Println("\n=== Example TypeScript Test Output ===")
		fmt.Println("File:", result.GeneratedFiles[0].Path)
		fmt.Println("Content:")
		fmt.Println(string(result.GeneratedFiles[0].Content))
	}
}
